### ISSUE TITLE
Dive Into Python 3

### ISSUE THREAD

**Issue by collegue1337** [diveintomark/diveintopython3#1]
Hello!
Thanks for you work!
It's great book about Phyton!
But in CH.11 Files - i think, that code (11.2.6,Reading Data One Line At A
Time)
line_number = 0
with open('examples/favorite-people.txt', encoding='utf-8') as a_file:
  for a_line in a_file:
      _line_number += 1_
      *print('{:>4} {}'.format(line_number, a_line.rstrip())) *

is not correct. (SyntaxError: inconsistent use of tabs and spaces in
indentation).

For example  this code works:

line_number = 0
with open('examples/favorite-people.txt', encoding='utf-8') as a_file:
  for a_line in a_file:
      _print('{:>4} {}'.format(line_number, a_line.rstrip()))   *
     \* line_number += 1_

**Comment by jkw** [comment]
@il-vladislav
Did you actually read the error message and checked your code for that error before posting?
