### ISSUE TITLE
Text error for string.split() 

### ISSUE THREAD

**Issue by JHSinKC** [diveintomark/diveintopython3#62]
http://www.diveintopython3.net/strings.html

you state:
“The split() string method has one required argument, a delimiter. 
The method splits a string into a list of strings based on the delimiter. 
Here, the delimiter is an ampersand character, but it could be anything.”

The delimiter can not be ‘anything’.
(1)	The delimiter char(s) MUST BE present in the source_string.
(2)	The result_list no longer contains the ‘delimiter char(s)’.

Result_list = ‘mississippi’.split(‘i’) 
Result_list = [‘m’, ‘ss’, ‘ss’, ‘pp’, ‘’]

**Comment by davipo** [comment]
The delimiter can be any string of one or more characters. If it is not present in the source string, no splits are done -- the source is returned unaltered (in a list of one element).

```
>>> 'a few words'.split('/')
['a few words']
```
