### ISSUE TITLE
The main page link is leading to a wrong place

### ISSUE THREAD

**Issue by Proteusiq** [diveintomark/diveintopython3#63]
Dive Into Python 3 online book links to http://diveintopython3.ep.io

The project is moved to  http://getpython3.com/diveintopython3/

**Comment by tripleee** [comment]
For what it's worth, the site getpython3.com is also now dead, and just redirects to a butt-ugly GoDaddy "buy domains" page.

I am currently unable to find an authoritative on-line version of this book, though googling gets you some PDFs (probably of older versions mostly) as well as providers of the printed book.

https://directory.fsf.org/wiki/Dive_Into_Python_3 has a link to a zip from 2014 at https://github.com/pcsforeducation/diveintopython3/archive/master.zip which seems to be from [a fork of this repo](https://github.com/joshgachnang/diveintopython3)

**Comment by Proteusiq** [comment]
Links are dead
